CREATE DATABASE IF NOT EXISTS bank_db;
USE bank_db;

CREATE TABLE IF NOT EXISTS accounts (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  account_number VARCHAR(100) NOT NULL UNIQUE,
  owner_name VARCHAR(255) NOT NULL,
  balance DECIMAL(19,4) NOT NULL
);
